apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLUSTER_NAME: ENC[AES256_GCM,data:E7iFNHF322elAs3v3Q==,iv:/46OFZWCY4U14+FZbJTpARyllu3vqXZBY70rDYd/rc0=,tag:/Fi3g/lTTmS0ckm0kCGqFw==,type:str]
  NODE_CIDR: ENC[AES256_GCM,data:958/bnsIACj8XAk=,iv:2Z+7ihM2DzGwHHDvAifdW48lrzr+6QFjpMjVsprzLc4=,tag:I4cfcgu3tEcwEyDLvEgrzQ==,type:str]
  #ENC[AES256_GCM,data:s0FiLDugYpYNwdxlxl4TyFcPdIL8sMMP1PorXnj/5C3rKXtkPBDKYxN9FJYdYAtomfyn7kA4Y8tIozMSkSKSr9uWCDEa93fs,iv:4uCyAPO01SO/iAUrptBuX7Z7W5fiGz6/JqkOGFTK2Oc=,tag:UM2VmVpEHZpC1rmcQDY1Jw==,type:comment]
  #ENC[AES256_GCM,data:Ysb6ElzidzIue5Zx0e2hGF0JjCWQOy956rFVfRnHxR1Lxw85ilP4CSR+wk6R7qKp05AIzRE6,iv:iOQLwvbYcyhpccfJT9sbU6Q+9zyCnN8V1U3fV51iBLU=,tag:FKOQxycfeO+7nxPqi6zmJg==,type:comment]
  NODE_DEFAULT_GATEWAY: ENC[AES256_GCM,data:vleaFk67G18=,iv:JqaCppIaVG3EpyAlpx8+xYBYNtELI2WGUnuitd85hIQ=,tag:Xz6aTAaud5i0ONoEC3JZZA==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:vTiCfeMfkC5icw==,iv:ErLUUDO48fejejRPGAyF0Sq98k3F8vaAchMiN7Grm78=,tag:ab39Emaw7whkSQUwnMz75w==,type:str]
  CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:usN/HcjIkZ9FeKB7juzKvC7cYahnf0e/F/Lz2rWTdYItlucVoVhH2nj+xvR73ZIDo+N3aME=,iv:YIOTrfJypgDyIksVhagfBDT1tx+2ki53fcJj1octuzw=,tag:AgMkVNCR+ctQ+zXFWGjCYA==,type:str]
  #ENC[AES256_GCM,data:2kgrLiAVj/dlYDdVXWWAX46pP+pRlkHMufTETrR3wsJXCKI8WfttJqZokRaZOvdBT/kqf0pANPZuz9/CopXIpJSYNwWDXlJuiLXrzg==,iv:1C5i3RQNKTmqJXpdH7yVUcI3PbU4lKJ7eWyVBCXw/+w=,tag:hLH49+wQitb1OugeSe7SLg==,type:comment]
  #ENC[AES256_GCM,data:PUA9hsJ6RK4ZKJYlZkpWCrch+E89kGKmGjHfktrlaF0bET3HAVg7UmgKHzXcpTIMMM+7545v/GD0uaihWhbjK1wN8TO5kDX1,iv:80DZrROtJiq4Bz4hcrYoNMJVqcU3EwJMmdEuDkW4QHI=,tag:0YPO4WufFaL0uEDqVmltWA==,type:comment]
  #ENC[AES256_GCM,data:viAtQxszer6EEK2Dumi0A3FQuJh1wdlURckWA7i3fuCBJsKGTA5PnDZ9kIqGm9nFgtb81XISNisa8bwxajddvCI3EPlVp79r9qFNCw==,iv:xfKLxUnunqjPIG28e2AJLRU+LEu2sS0SUIIFqWKakfQ=,tag:4kr6Ft3e5+bdJirALp8GyA==,type:comment]
  CLUSTER_API_ADDR: ""
  CLUSTER_GATEWAY_ADDR: ENC[AES256_GCM,data:fCjsV96wmM9lFg==,iv:h56H6V4oH4YmRS20yMBS6oWo2TrUpzIsU5Sz6vc2sAI=,tag:PAgyETBAVGM3+HjZxvVPXQ==,type:str]
  CLUSTER_DNS_GATEWAY_ADDR: ENC[AES256_GCM,data:h2zyAjSp2ehT2Q==,iv:To0AXG8wJe0vUZ6WQTz5h3T2ww8PqVTSZZwXsMu6hXE=,tag:YLIFCCW7VCjvjn5A+bNmDQ==,type:str]
  CLOUDFLARE_GATEWAY_ADDR: ""
  COREDNS_CLUSTER_IP: ENC[AES256_GCM,data:4idI1XWpXKhpqw==,iv:W+ub3XFNx0/cKzAYg+bIdhMTAw41uQQWQhkIrJhrbmM=,tag:P0djCr92gcx9ejX4lcXUGw==,type:str]
  #ENC[AES256_GCM,data:uUp3TV6R8LIJn7G8RZLptcpyZ/iZFQG4Wx8N/z1tzKZ1deGT7DcaSgJ90HQb9zqw9f4mN+St9/awjozbkgBuRUSnq4ysvC6n,iv:N1Hhtaeam7bNWFWQbaOVy9R3niZElKU68zzeuoYA4Gc=,tag:zp+I1s9HCrN9x0wMQHRfDg==,type:comment]
  #ENC[AES256_GCM,data:rsKzNdfMZJkbB/jlbX7fJfBf1ivRVLD/TvkYuZMkOU8319NYT85K3mpULYH+93Q5NaqS7cfAdNyg2y5k+rLtFZ9Dvn2a2w==,iv:vowouMvN6ktZ7MnhMA+/wzUE8y1idjtV4IZrbHtFsbE=,tag:c/bjMhvuFsjBANEue5wQhQ==,type:comment]
  #ENC[AES256_GCM,data:1WQBaFjDc2Fkgu0oevKTFlFGWakWIqZwuESIOGsmcmg3M5/2L+Z5/DuyPwN/e6J8qiUAIKi5gVKWIDxjgc9o1XYDim3EgzxmEg==,iv:8Y5pcx+IwxskdufLr614M3zhD3nB/8wxEFaoVnsNf+0=,tag:fdn14+ikVepbWsIsdvsdpA==,type:comment]
  #ENC[AES256_GCM,data:g6tLrLix+RCEzIX8j1WBbY017hRCM5Qs+q1nAbMKEJIBmJFx+01NxUMEBC1EOhgDKY3rCj3T+PIuf7x8E1R/lrxYWtSP7ReTk00=,iv:6CBa1FoUmg6MvpZpSMF/ZeqjwxiLYitvEsiy0sFnAJw=,tag:PBfqSKMSDHNzlz00qnLq6A==,type:comment]
  #ENC[AES256_GCM,data:4wmTOOuQUK3PWualgLkh2j4gMCxBCmsUJiyr+CVmr/VI8U9S7pMGBxVdjwhfte1EBQW613C6lO4L,iv:rP8eJKN9CLRteewYUD/Ny8n7I5E/gRB/5TLZtD3v9gI=,tag:HSoDDd3aztWsOOVS7MCOqA==,type:comment]
  #ENC[AES256_GCM,data:3vfDEHQ+1RUBmNG1tZPj8Qw59VHAbcscCsamEbQUyHHH/nVWa5QERuGVblE2Dh7zNCsoRCkpMeL82yApkSttrkcisX7AXEE=,iv:B2TM1Z46HaDbyfXkp98f6qmRzcvvnr/v0TtTFjy3xuo=,tag:/+XKgFP/SEIbQRtCb8MLeA==,type:comment]
  #ENC[AES256_GCM,data:A37xInyV5AuD/qyDAz26IGEJgAf98nxGGcMjaZTgkUV2sKF0R+QWW/TU8eBhZ0HwTY9e/UUsnjewah5UdIp9LjaZHgi9ALE=,iv:wS97+wX4DYX8LA4iRJXkkSykK1baYJV+qAHNlACnCcg=,tag:PSfguQoMwh4dtROLevl3ww==,type:comment]
  ENVOY_EXTERNAL_SERVICE_TYPE: ENC[AES256_GCM,data:dx8g0ymv4b8kyyzD,iv:NFiR41PN4ga0Exn3JqiqizEL/MELYYPT9ibN7FYYzg4=,tag:3qJxWA3qVjj73Y1EUr75wg==,type:str]
  LAN_SHARING_KEY: ENC[AES256_GCM,data:NwAV,iv:sZESCqAEXIYnH/Vfj6w8bDq6cicTh9+Gz/S1Iij9gho=,tag:wLULougWbJmPvHOsaZw/9g==,type:str]
  LAN_SHARING_CROSS_NAMESPACE: ENC[AES256_GCM,data:2kfgv/RWHkif4Vpt,iv:CUnoXCcZ9W0EGDWuMJvZCbSAvV7pvXU9poxF6MOejV0=,tag:od/jS/UhUncHfLLtG3RTzA==,type:str]
  LB_POOL_BLOCKS: ENC[AES256_GCM,data:8fI=,iv:KAuZFhjbyqdBNkNF8eztiVEndz0GVNz4nt2pRjG2q9U=,tag:QwfskCDpPt8YUc4LBRLwVg==,type:str]
  MARIADB_LB_IP: ""
  OMNI_UDP_LB_IP: ""
  #ENC[AES256_GCM,data:AqoeQwMBBn4jkokpCJz9RfWKIl1cymQDBm2zUGyIef7Xmnqfl0BNJoAuh38Zo2TVUPUIzl0MF9QjjI8ysg==,iv:MFG33DQTepWzgiIphEspwqTsUFYN+Kdgzw0rsVx5JYk=,tag:+A4DbwLFbVX/d48AIk/yRA==,type:comment]
  #ENC[AES256_GCM,data:qhyd6fSU/1vBN1Ko/s/6wYNhkv/o4Ah5YfepcD46WPMnoIDRQy+fuC+pa0fXa5bvpAlnOPFDD6wfVj7n9yqdYLw=,iv:QJtD0hZB1KDN1d5pmQ/c4L+SNfrtwEtwVCT38luoljE=,tag:DEujhdsmRx6bkdgJ6gpFXQ==,type:comment]
  DEFAULT_STORAGE_CLASS: ENC[AES256_GCM,data:Pda08SG0GBlPIA==,iv:J96aeeGW0UVmO4GOxMq+p6oXtBZTekS1wG3NY6MhfY4=,tag:5j1XlnLjmLbXksFP7tumMA==,type:str]
  DB_STORAGE_CLASS: ENC[AES256_GCM,data:jIPGSnIpU39obQ==,iv:nSG2YejspE6wF0JW/kApo2ZEmp7sMT7vnfGA+JPbfBA=,tag:eX0hdDyH7npdi9GMeQXfmA==,type:str]
  LOCAL_PATH_IS_DEFAULT: ENC[AES256_GCM,data:GktAQw==,iv:4wesPAuJuLYzGm96BolgjgdqNBjd5sdk4/PmlaJXMH4=,tag:o5r2wvjmz/l99w3XZ54Aag==,type:str]
  #ENC[AES256_GCM,data:mDzWN41EagRUTvBoNDmdMCztXIdf/kzftruMAnztcewQw2NIzBo=,iv:xX1JbGtywdBDgr5YHg1gYLdlBKrgCROGBvv1+JrETzY=,tag:nmXyj4q6HLdw0X6/AmHiFA==,type:comment]
  NAS_SERVER: ""
  NAS_PATH: ""
  NAS_CODING_PATH: ""
  #ENC[AES256_GCM,data:taI4mIYpgk0rGGFwusiyG623kXWEmkRKk3EUcdsFOqgyNytBlS0/6+T6m+9QBk5LWwDjZCaI5fZrh/HehqLgvQ6GD3KzAbcucKD/,iv:hSm95EiTYTfDKFF2OsIdeYZ7f1AdK8CJy3tICBnrXuk=,tag:SJTiiAfZcLmF+fDhhMJohg==,type:comment]
  #ENC[AES256_GCM,data:DJXJqkRkAWDG9tbDY1d9KG17nWl2dSPxDG2SZ8T2w3xanTMbvxj6WXaSZk+PC9wvhadVF78vsWwqfh8Swb8MNg==,iv:S4ZAfDHP041lk3xNDNZmMZFkQ2pR2zI3fM5hlxAPFBw=,tag:A14XE42O6VggHDk6ZhllwA==,type:comment]
  BACKUP_AGE_RECIPIENT: ENC[AES256_GCM,data:3KHiwP6B86QEwYYJwTEWu2kJXqkjlyFHGm/zfyQNl2pAxEgWjkrVs8W4vDBZhwHAYPGBYYIBj1V9UOMZfYg=,iv:gP8o/MYDIZ9ZSeK7izKamnYEquFDbo9HJ/VBEmMfp3c=,tag:jsE+CWNDhxB+vI8Z1eWtfA==,type:str]
  #ENC[AES256_GCM,data:dt8LodG6XZbg4T0fOy4sxdm//9P+GLjgYZzIOXK0RpdsiVPs4pzJ4xfCx4OcY4lPET3V3LjEUgFKg7AR7z8EbN51SNg=,iv:zmXZSXFmmQeAc5cLYBhLB2itN4edrXeNfGRoymeateE=,tag:w2bS3j0JfVoEGjIz7AdhLQ==,type:comment]
  BACKUP_R2_BUCKET: ENC[AES256_GCM,data:m8KmKm8tB0YCiaKTSPq47mAcgwg=,iv:lNZrvG+HfpI4x2UzVgwIxBb8TJ/F2F4Y/ce4R1VbMFA=,tag:fQIvwLqctVwF7oWs1cms2A==,type:str]
  BACKUP_R2_ENDPOINT: ENC[AES256_GCM,data:9oOwf428bzcv7drE7QnaIADWx9ajLJymCcsBnL74IysxzNDWlXQ7dXViRjfRnqv6TTNtUmkGcPknqfj2djEEaTU=,iv:c3c3pERSFntOhOs2kIkleJObQEbMivGWkvL1dIYXNEg=,tag:1o03ar4v6c3fqIyy7RKWNg==,type:str]
  BACKUP_R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:6rY3Urua2ZG3yl53ATOXC1iqdOdNt1i/85vwDZSAp00=,iv:G4/bb7JhwlwIKz3nL6esYDUviQ5+Lgz6j3w1DIIW9cs=,tag:bNDhLhGwumKt0wSf+MvEfA==,type:str]
  BACKUP_R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Dvv/LxKskqwTQZurhz+QuRUHukMHXX3qfOHloTIh3qWxJ2N99uBRubhsW67dZPjMIZ7X1Yk6JeotaAVMLdrsUA==,iv:/QGJ+Tt7RqBvd/NNrGP4FM3qJ/JNvYlv/0j9+gUx3+8=,tag:3mSPplKkrfRTPXWdJH48xQ==,type:str]
  TTYD_CREDENTIAL: ENC[AES256_GCM,data:5/NbkLJpv8FZ7XBTJZCJuK6lvTOxBW/XY/jcFRrhBt0Us32X,iv:CNIgUjVmTSyTdKIcpZkFb6w1uWSi+bbzGPz+j3LmU70=,tag:lLZrTRaNwFPwPmInuIT0QQ==,type:str]
  CLAUDECODE_AUTH0_CLIENT_ID: ""
  CLAUDECODE_AUTH0_CLIENT_SECRET: ""
  CLAUDECODE_OAUTH2_COOKIE_SECRET: ""
  #ENC[AES256_GCM,data:FvzkoPXQDeNoZ1qMXV/dqsSIviwSgL7UhQlPkC5DJGXAz0oPreDov+rP61BNHXQtpv+6IHvZjlGplPY7hMBObyCPvQ==,iv:zwg05kOarBWxu85vqJchewd1NlSyBuiMPWSF3oHQ1d0=,tag:JwHZe4lk2ngvl9NE5Ai9ng==,type:comment]
  #ENC[AES256_GCM,data:DM/0ylnTE5V67hF/JpbA9HchOGo7NZbbjlGHtgC3KKFM1OAZTyQxggzxrjyAJBdVVP29869rrcJeXYeObSrFRVevXRm3,iv:KtJvgpydWQKrire7H47auaSRPqSEcSrK/zO6LixY/zE=,tag:DJTAOgbMHivN127xkyR16w==,type:comment]
  #ENC[AES256_GCM,data:MVS1ZKQ8oHPRP7VUJFGf9dKRehPC9wR6mtOwZh7mGccS3UhbOVzcuWzIpFmWROATdMtzkXsx/8syMz1gNP4D+JtIKj6ms2E=,iv:IShRDFSpJJqr542eu847CJlf8YRy2nB4RkXQ1zaaIsY=,tag:vQiPtkYdaxiBBUYpvz+r9w==,type:comment]
  TALOS_MCP_CONFIG_B64: ""
  #ENC[AES256_GCM,data:pG6rVpY2U0IWZq9ZOeQorS5Pr/srrvpvM5yN2LMVcrE7psYBtms2DJNGMaMk9QWIc4qp3TqvIuq4LfwdGOHJIViv0SNdFQ8oftM=,iv:bKLV9W1sVhL6aAnpufMLQaBV5I7pgl7aQpQUmmklgck=,tag:QjqXTfwD/WLW2CePn8g+Lw==,type:comment]
  #ENC[AES256_GCM,data:8FQ++SPL62Ay6LN91SZiw4x6UcEMXKTgwADSy1RZt+MNL6Y7bWWIdw1ZyfCmhshF+8cVS2fyDTAhIGS6aDhBOzs1xTBmstSY7Q==,iv:+Tp//16oBsqLb2hPdAlaIJ9eAYjcJK5Uhmol2h2mmR4=,tag:7MzxWs+G9/yWGflt8habzw==,type:comment]
  #ENC[AES256_GCM,data:WwbTGOe0i3Jz21GjUZDtbiWO3fNkBIbGP1XBty4bPPnYlUzXkSjAiJsHmSZeXKCxYQi/DkwJvDL3o/ZlPnHNtqlywMC7Fldgfw==,iv:YsfQECMF6IdJhsUTClJxynoqUnw63gKfUxh8BysO6rk=,tag:lzXF1AkxG1A7ZKyvdf2x2Q==,type:comment]
  #ENC[AES256_GCM,data:LX0WMd3P3lGj3n98tWCvvOYMqER29gaMicksLjk1LEKuemfQwqxJJqcqh6JPb83SBVWIP67MqeNAXCC71vBxtHpXWhdZIrYScVBZOw==,iv:Tf8+26QtuF16W8wNn/J8BzIH5iGfsyjhES4ZVsU8rPE=,tag:PnRR5zYtNyFsJTNfMHBNHQ==,type:comment]
  #ENC[AES256_GCM,data:DOIDQy7Atmex3qbJFffnc2e/E2TdsxjnJ+nybkhbdW+1DInQbhmhe0RM2DcVL2etXQC/i5WiyoWZ8aE3glBvVa/DxzUVxizScA==,iv:zpDF9ZTdqB6hLWBs89kS+VvlpR2WsmhynHuE7bDBm9Q=,tag:38qe+Ay+WI6YUJV5L5iWgg==,type:comment]
  #ENC[AES256_GCM,data:tMqjtZizLPeGqmrdtJOrXzvpE+EuLFu/fItS59NKEEwRWKLPL2/5H23FzaX4QHaxkydoUAl0cbiQ7LzftjWsc90OHLMLc3o=,iv:QBhTuoEcCOWFt4dvAHYUvya8SW7s1EgNRJqOvn13W6M=,tag:AIKs1OAZuD3XIr3cusxgAw==,type:comment]
  TALOS_MCP_SA_KEY: ""
  TALOS_MCP_OMNI_ENDPOINT: ""
  FLUX_SYNC_URL: ENC[AES256_GCM,data:y47hmRhLkUtS96Rw2tQpoN8uZmHPhHajT7SkzrqxfW3xauxuz9uOat/e7Oly,iv:GrU2E1YbzIBwmcOIjagnxnEx5q3BQAFk9pwvdvD9wIw=,tag:0BmnxCx1Nru3KuIhMPyYSw==,type:str]
  CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:L0UWIw2Pc1cmx3JGzW3otyd5mbiudWmNdL79/gBiRoOV7l1bW6AE4Yu2PuuKxM0Y7+HXB8ySt4Y4OPihoOErCLp3ipVMZoL4AZstfWDf2lNIonSxOJesY6Jr/fARK2UoAV8VurjccGQtX6cwKNj8h0kVVO2gBpL4cwX1LOnH8iGGs9lVhd/quA/y/1YuQlgCeI8NI3BsuYna+ihv/Xbe7eERc0ySuqM8qpruBmgc9HC8s5DE,iv:cmlIg1y9APhZoQ+1snY4300PCuoqHgWTKUEYUEAyacY=,tag:SjtbC7LeF5vXyeP+KpC7+g==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:/WfLxZNrpnug8WBDiEN4cqfiUQieDvtfxCmrRfejl5fQiv5K,iv:Fzii/2X+iJC4KpuLZYoKg8oN+CdfKHxeaZxNpTYffcs=,tag:l17OIAR84gSCvX9ZfdkUvw==,type:str]
  GITHUB_WEBHOOK_TOKEN: ENC[AES256_GCM,data:0D0u4Jg6oHF/r7DIXyUyvaWhHoC9D1ARgt8rFRCP5iMf+3ichFsYzQODhwyxQdl4eVRNLgYRWu7arjmTgopv7g==,iv:VHI+0SscmddWewRy6sN8X4Qmi+DMJZvx8TMyedTzHvQ=,tag:rLRjm0ixBXfWGUJmN/W7pQ==,type:str]
  POSTGRES_PASSWORD: ""
  TRELLO_API_KEY: ""
  TRELLO_API_TOKEN: ""
  TRELLO_BOARD_ID: ""
  LINE_CHANNEL_ACCESS_TOKEN: ""
  LINE_CHANNEL_SECRET: ""
  LINE_NOTIFY_GROUP_ID: ""
  ANTHROPIC_API_KEY: ""
  DATABASE_URL: ""
  SYNOPHOTO_AUTH0_DOMAIN: ""
  SYNOPHOTO_AUTH0_CLIENT_ID: ""
  SYNOPHOTO_AUTH0_CLIENT_SECRET: ""
  SYNOPHOTO_ALLOWED_EMAILS: ""
  SYNOPHOTO_FLASK_SECRET_KEY: ""
  SYNOPHOTO_NAS_USERNAME: ""
  SYNOPHOTO_NAS_PASSWORD: ""
  FREEPBX_MYSQL_ROOT_PASSWORD: ""
  FREEPBX_MYSQL_PASSWORD: ""
  CLAUDECODE_POSTGRES_PASSWORD: ""
  CLAUDE_CODE_DATABASE_URL: ""
  OMNI_GPG_KEY_B64: ""
  MQTT_LB_IP: ENC[AES256_GCM,data:DYvyfGNar1q6Yg==,iv:GvE+EekX9KAUz5ur+8tRAr2/JxS8EMzkNx1rauxvpec=,tag:GNbmVZjSyALMCK4s4fcClQ==,type:str]
  INGRESS_NGINX_LB_IP: ""
  CLOUDFLARE_LAN_TUNNEL_TOKEN: ""
  DAILY_CHECK_SMTP_HOST: ENC[AES256_GCM,data:w1CzyWFn+3zWJW1PlMY=,iv:jNAlejAaHvqdJx2q4hYONZQs4LcClnNb+WAftBxNiTg=,tag:XopB26wikrXHTEqJ6LS9Sg==,type:str]
  DAILY_CHECK_SMTP_PORT: ENC[AES256_GCM,data:UYzW,iv:nOGerDsem4o/md+4CWEfUIrUks5iRrU/VfzF1Ylduko=,tag:4bg7AOeMjQGgG8zXgR2fgw==,type:str]
  DAILY_CHECK_SMTP_USERNAME: ""
  DAILY_CHECK_SMTP_PASSWORD: ""
  DAILY_CHECK_SMTP_FROM: ""
  DAILY_CHECK_NOTIFY_EMAIL_TO: ""
  DAILY_CHECK_HEALTHCHECKS_PING_URL: ""
  DAILY_CHECK_ENDPOINTS: ""
sops:
  age:
    - recipient: age1xn7sufdlltrdm3zwrxymhkyw8slret5a5856yrxekqmk9tz6culqypuy28
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxY1FGWHA4S2swNW0xaHht
        TnZIOUxCSyt1cmw4VGo5K2U3eHJHUDB1TlhrCjM2SlNORTVpNy9qVGJTbGtyUElq
        YlRrL0JpcGc4bFlhMFFZMzVsdTlvOUEKLS0tIFZybWNXV1VwSjZkZDY1emx0R3hw
        TDYzd3M3NTVYKzJDRkk4MDE3UUJKY0kKlxrltC+aVk8Upztws1BMwJHi25kgnw1o
        fV7qMR2Ho9Z65JFPKySFa5En04rMlDr63b/fvsqQsEQVkLnUJQ9Dmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-16T22:57:31Z"
  mac: ENC[AES256_GCM,data:uwBe6zg17wtLot119q2sX94P09VJJ3ZU4IvUBGqmP1GnVCQZ7ibg71F495SXAn7Hxwyeyi4KbI9RPaFyJ8RuzKB3JzO967+uufeDl3/gEY2vNX427Bq9uN1ms1K3OBQYjhWdO/YEXbenOIdjkKHCid6im3fQpoWHNbfeNaCbFUw=,iv:cEMGoJqa6QoOu+wmHW9LbzccOAhy4CBXGs16FlY2dls=,tag:zvDWoDWwZFWINbz4WdjrRw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
