apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLUSTER_NAME: ENC[AES256_GCM,data:nIjg2zpN3EgnCKnd2w==,iv:0mn60JuRZUTUVi0eELBVJQaSNGetruZIgoRt5FVu1SA=,tag:gu51fNaV7SdqPy23lFOxNg==,type:str]
  NODE_CIDR: ENC[AES256_GCM,data:VJ0l+UYo0aigOAo=,iv:beo89UScxeJqUtBZFmOXHCey2fiEOt2Vs6i+oP7TT8U=,tag:7orSRsu9eLrJ96g02nD2vQ==,type:str]
  #ENC[AES256_GCM,data:DsDsQfAUtkuryeL1ZFOj8BKxUSSbFcbVDqx4tmW0/zSAHfxrO862uO5BpazotYAOXKVBCSdesjwnhccXhig0b6QTs7dekCF+,iv:cwRz19RVb3VOPf7KThvBZ1qO6zFDf2ctXZm9Y/29Q6A=,tag:pM51kRUPbtnWqJntpnP7kw==,type:comment]
  #ENC[AES256_GCM,data:yntR2WBPzsir8jTjEE446TZ+t+bHRf9ENmqLYZLbaarvoJpUTka3rzKmTeeDFG4ae8UAHvoJ,iv:2MhxBHiGvjcwKMkrQ/t/9SGDig58IhIzclqeyxj/QQg=,tag:OJKMV1m/wpitxQFrBmG1xg==,type:comment]
  NODE_DEFAULT_GATEWAY: ENC[AES256_GCM,data:AUFWWJsXzgo=,iv:PdZvUB8Ia3r8qAef5gfcIaOOntalFGAZFv6f49cVgeQ=,tag:sIL5pjPqk9e4bYN1fz5/6A==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:e0GklYCM9tP6Gg==,iv:GbCuxtwUUEB2e0jw2kMsqq2lQXgsHDTVilxWSnr6Qmo=,tag:0xPIZku362e39OHSLXgsxw==,type:str]
  CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:RPYUaF5gpb4bsUAuczHWaqhyz0zeqPbAO5lWDoLVVEF4sLvsUhcIdnzuGq9LGQdDNbZafts=,iv:EQxcAEjMmuh6+BhxSYCTDA5GFC/I/W49XFXAj5oKKhk=,tag:eJH3A2KXVmlr2c2oGfnvcg==,type:str]
  #ENC[AES256_GCM,data:3+4nAOeaaxB2LsjLRbwllrxaS987mv1rTni0oqWnYVicQJCLT4AALKT+wQsgVaR0hBp4OYveNbeDLq5DyZzgSc0M2mtghLUmTgn6mQ==,iv:tZjdVS00ztwmHXiSzLba++xdUOXfIPakUkXc0lysZkw=,tag:MZH7oipjQwuIET2rwGDKKA==,type:comment]
  #ENC[AES256_GCM,data:LlZeNxGfJxt4Ax51SqWIkEGR5pS/fPWdoWfnB3AgqIfg7UtZUcXRmuz/83jT2xde7AIlonfFV+MmzeloHLtfQCn7uTReak2A,iv:t8spDbci0/XliMYiqsxVqfjcqxVcdZf/0/OvQKnxo3A=,tag:sztLc+owGBAhPJGbXl8VUA==,type:comment]
  #ENC[AES256_GCM,data:sfiTO2s5egWc1wKXWe4JXjiGxddmRPivpmylh6lajNOfSXfaDEc8Q1SvyWurmwHZXV4I8XB5boklPbcZ5cUE2qWQSCSeJHOjKAy6OQ==,iv:j+oS+hsI6jlDE9oLm/g5Fp6iZhw2qZA2Tk63P4AxBtU=,tag:65dHhr803C2MAR1wsM3Brg==,type:comment]
  CLUSTER_API_ADDR: ""
  CLUSTER_GATEWAY_ADDR: ENC[AES256_GCM,data:2fG3b/GjvWX4NQ==,iv:yqn/jWo6pTnTJmLQfXsOwNc/Rtdqpv1AljUVVxZKORg=,tag:Wf141MnBX9C++ja7djWBsw==,type:str]
  CLUSTER_DNS_GATEWAY_ADDR: ENC[AES256_GCM,data:XXQWAR777nPWVw==,iv:GBMMykiJbGZLYMtPej9uNNcjtQ/es8mJgGsXSv/h9qM=,tag:/nHAwx7yRi0O49w1OJCiyA==,type:str]
  CLOUDFLARE_GATEWAY_ADDR: ""
  COREDNS_CLUSTER_IP: ENC[AES256_GCM,data:rZ1LzVbkuCC+Sw==,iv:EcGYe5IjG6Bkj3H3/UBMIk3l3lzdOh7Kr6QxapsyR44=,tag:VMxBCWXP8cSh1hkqHa2l8A==,type:str]
  #ENC[AES256_GCM,data:DpKeS5HBcF/Q+Annu4CxMp5wubypDboHywmBVOfGMnhYgJ5M1cBWFuc518V3bm1D6BvcZAF2hLLhGiPKVXHOGpTTOqWsiZXZ,iv:/LVHbD8Slw/ikyK/vi8spQHgFSvhWat+UEUgG4XM1Qg=,tag:7zIAK33ErJXP85xjwECOKw==,type:comment]
  #ENC[AES256_GCM,data:XkLMuNTtpabkazMwYPxDpuEd3oroxAA/Emg2JHY6oqbahN1Ggi3iSQGv0Yeg7azT7AxciV3D611jmueBE/wVPbUy9FRMNw==,iv:PeswveuUdC2Jdt8t3/MQCuYUcUHbykTsIn0MPKRPNRY=,tag:moCn1qjrH5JLxZWCyepnxg==,type:comment]
  #ENC[AES256_GCM,data:6X+jrP/INxPr+fLhy6p/HeLMOE6ME7lLKXSGPxYqSO3ZxVpyt/+/SuBm1xp64X0xGghaM85/ceCAxvQn6YdajavOkjTxTUCnUA==,iv:sBOY4dUWbEznUgdoJWFWbrTJJZN8yMB3QJg7qm/boDU=,tag:XLvLFqRKcu5lZ4wuT5yOcg==,type:comment]
  #ENC[AES256_GCM,data:5btvQy4SVmQ1ZYOPKFYQ8fM8gy8g1foGnDCLyAChllzf4yA/GDJvzqn9DIpJZXz3s21dwuWAjJZxughdjV/c2js+RAKKwIuqbww=,iv:VgC78LTtZ6XF4bYxODNfb9+pbNuSPHeml8XsNZ5NJko=,tag:9KXxGGQEdMfRFNvVEaLnBA==,type:comment]
  #ENC[AES256_GCM,data:OhMMJMunNokSRDUs96cc67uaXlclMe9Ke4Iuho0arUzDm3r4I81LlJHj2NT8IES72GZxlD+oGvxU,iv:gbleSdkj2EerABSV88jtDmR6LFiu6Ii6i6Nv5JUGoiA=,tag:U4sKzWQGy3jSRWSxnElqbA==,type:comment]
  #ENC[AES256_GCM,data:+hWoDTf+bx5XPw/S+tYsNINWp04Oxh1g906dOwBh4+cCoDQ0/ocL89v8P2BtIVrQEInAnlJ5ny59fO2x9+1xh1KWp0S+vno=,iv:FA5sX1pluGH+mcdNvoOhp+PzSN2ozASYPEXACXQpqW4=,tag:QVkgna0rJkB5IG0u1mkVsg==,type:comment]
  #ENC[AES256_GCM,data:zfEWlV96gyv4EfwcWlfvQeVH3IsIFL572RwgoCKqw79/M1iroGGQLTS89Rbllkcpq1srqu4KlCLpMD0NSLaiffHEhLJzinU=,iv:9ojHAnfkJzPJcsdDlabMKf2ThldTy7y8eZYPBmRaNMM=,tag:9tgKrRaaFA3J8/3zw/yRnA==,type:comment]
  ENVOY_EXTERNAL_SERVICE_TYPE: ENC[AES256_GCM,data:Q66+4AArnToVBKSn,iv:rnZqhpl76vLajxpWJiJGROagzhbYRz2OjlbobFkFJSM=,tag:n5EcDJoq5OtWJXhcMLLpnw==,type:str]
  LAN_SHARING_KEY: ENC[AES256_GCM,data:9/NO,iv:PaBD3zMuKXtBZVLw2fRIPm1nR0g93u+38mbHH7oypaw=,tag:TCIocQDD5Cgt17hAAEhODw==,type:str]
  LAN_SHARING_CROSS_NAMESPACE: ENC[AES256_GCM,data:ipqJEOmSsfoY5IUm,iv:+v+Th+3b60fw7sG92oV5+OPIBiFt38cp8wcRV1N7uws=,tag:AY/PnFDvJ8AInVdMhqkbxg==,type:str]
  LB_POOL_BLOCKS: ENC[AES256_GCM,data:kqJmAmapcx22LcvWfvO/6wK8jks+qkeJShnDTUE+x7rch1Rkj6wEOVp3Spw=,iv:DF0fJ3v5L3K6R/eo7TcDb1PQp/v6JbSqOavvUw+lJyc=,tag:JyXyQOulpSLoBbO9GLs9mQ==,type:str]
  MARIADB_LB_IP: ""
  OMNI_UDP_LB_IP: ""
  #ENC[AES256_GCM,data:/H5oJWOa7JhBgWmLT+/E/bmbHu+QI1K4AhELzLRgUJivr/j122arWAXMHdq4g10m+nlVSbTwMG2qW8g0UA==,iv:j2j5lLtvwddv25DsR/N1H8hqHsbAKwXu89vwi+7sRKE=,tag:T5yXkFqU0SZR3lp1SNxAMw==,type:comment]
  #ENC[AES256_GCM,data:6MIIQ1q3w3kqC3qoB1ZbuKHpfNlegut9iwve2PfSDVpsoZSYcH1VUkhzqgnGyaQqS0osvWirji9hBtD9viPfafg=,iv:NIGOR+7cXV6BtWMpC9HSYO7d9TuAJYegVpMsmDOQg9Q=,tag:Zvya9WBSOyghp3cM8z/+bQ==,type:comment]
  DEFAULT_STORAGE_CLASS: ENC[AES256_GCM,data:ErgoiWnJqdEHeQ==,iv:G3Jm43gkX9k8PWqmCK37srfsHNYv6fDkQ20MPsevSNI=,tag:CepLgtuZ3//m4a14wrU4Fg==,type:str]
  DB_STORAGE_CLASS: ENC[AES256_GCM,data:lXiBOHQKkEB7DA==,iv:1+YNKlczXKXd4pudzmYXvG330Jk6JLkexi+ujuBT98E=,tag:+ZIiB6ADKzMH+N5/DQTdRQ==,type:str]
  LOCAL_PATH_IS_DEFAULT: ENC[AES256_GCM,data:R7QGwA==,iv:79JQOEuelSDzlLhnPfPojwMRA4ky0B1kERMa06K3rNU=,tag:Kz1NwR9NF2BGve1rXL23hQ==,type:str]
  #ENC[AES256_GCM,data:RiBO+udrDjZLsBLgOEc+Jvv/LlfHkROqDuahwQs8dAXBVsY1qJQ=,iv:9OVJqqxvIkePRUEBXqsEpTSYYdPVtddiUpRFQ9FCoGw=,tag:QfTHUzpyoNrOqFewmuhQOQ==,type:comment]
  NAS_SERVER: ""
  NAS_PATH: ""
  NAS_CODING_PATH: ""
  #ENC[AES256_GCM,data:F0+A3YxkwVzINSlZbTJmiyVlBb/nnrJhCcV/60RBzWeknUMY3sXhVA5E6KcEkSXaE9ncCKrDNQfDzNFZEqFYFLM8dtYXeX20zAAl,iv:3ei2FKW45wYdqhu3+4DSzCoXtwK1b1/D+W/wxqUv8kA=,tag:LDrZ9vSYeAMbGGJrpMTchA==,type:comment]
  #ENC[AES256_GCM,data:DSlQVNMNzgXDKaYqrovCIxEkIfYzN7m/rcLbuq0ivbgdBOht5dI+qVhYA3EnO6qGezn4UhKiOq/mnnrzLp5wkg==,iv:vgph1jaxX9ksac820FYsLkfwe4IAEsRFwtcHcniLsR8=,tag:UAE2NBnmxawtreY44D6x+A==,type:comment]
  BACKUP_AGE_RECIPIENT: ENC[AES256_GCM,data:Z8aIPJZXy2GMWEZ3vxt3ZSsUWDX4s792JA0rkqfUNIjys5DMaid7x4LLqtbixyHXTnQSkJQsmWn8km16xCc=,iv:XYEAXGXxs7V21d1pdUDU+sRxxKp5TS4ys7MIYA61s3M=,tag:wm7nHBO3Q4za031Z6KyUBw==,type:str]
  #ENC[AES256_GCM,data:LvRo0a7XB5HIqpPD+eDykWZlbxTleAZqT9cKTYCEdlQpgmOev5kX/UStiPLCis3+C1OViYO8JnyJIMKL13lHj4+Mw2w=,iv:hBLP2a2gJBMYkcqTkdTpdH8mKT2ZHbKkM4WCCQKTEJw=,tag:gUetFFQSN8a+1l4mQmP+sQ==,type:comment]
  BACKUP_R2_BUCKET: ENC[AES256_GCM,data:cVUam67iZGXo8SSoOtOnhQ6lmhM=,iv:X3Iw9SX4t1DHnOW8anY8RU7HghPkKmF70PNzWXqhhG8=,tag:T1V3l9Mblb5DnaGSlPUBNA==,type:str]
  BACKUP_R2_ENDPOINT: ENC[AES256_GCM,data:KmslrDBKYapPDSHi7YGEmQbgXnHQ76w2jHfvpImGNzE5CcVdI9rks1nuoBYvUe9o7lPjxXzo/YH9cyZBTTrvGp8=,iv:PPEwiZ1zqlddxmB2O7PDuX1j+fa3CaHIoHivMihjcy8=,tag:M3pXdZnmJgZRG76zPYA+Rg==,type:str]
  BACKUP_R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:RiFycYvSwWtS1Qvi5C9zcAThumrYc6DQlfANTr6MRZU=,iv:HJ+9FoLbzFz5eI85di7Q51wXjSPQ/Pk+1cHi0Z/ttHQ=,tag:4WNrtBSJBk/ojKMGOCzZkQ==,type:str]
  BACKUP_R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LxtiD2+mq5A7xMddETi44QFSzs0yvEg0bBufGhxDLP9NLt5bwQ5EFXI3+EWgirJQBde6CW0mO5MR1+fO9fEAEQ==,iv:JWyYFjrexVz61PVdMU19P0rQ22JEPT34DR6VjA1JShc=,tag:MjAs5N+uLJXp1cqW7TtiBw==,type:str]
  TTYD_CREDENTIAL: ENC[AES256_GCM,data:k5szpWeI1kaVN9EqVFs7TkYmSfXk2lbRo5w/IDo2LxEbph5+,iv:b7M3oCr1LplikXB+JH0FA2g+BdnU5g2zy9bh8g6fSaI=,tag:2qw+nVO2VdJAY6kJu8lzoA==,type:str]
  CLAUDECODE_AUTH0_CLIENT_ID: ""
  CLAUDECODE_AUTH0_CLIENT_SECRET: ""
  CLAUDECODE_OAUTH2_COOKIE_SECRET: ""
  #ENC[AES256_GCM,data:9yWRig/o/BnrkBiSIjd3m3aoYWQAzTiF++xBjBr9CLTpj0ZydWjzV3H/U4GvUNDO7EVYD7nBXY0ERVc91SfGwu17gA==,iv:I0uBKQjA37oUxFUiO7jnmMbHZYa7zlGKJNCIWZb+Bx8=,tag:Tzx3lZl6y9OUg0poDB0p6Q==,type:comment]
  #ENC[AES256_GCM,data:K442Wi2HwXUzYOl1b06R3gGMXFllF3ZMkzW1miCTBbbTJS4DtjbOIJZBgR/FXRexuCVlu8iE1RdeAs/coz4ji1alC1hs,iv:s4HxMvGxhu6/kp9ETDplubmge/o/Mk4gXlbEG6q/64Q=,tag:GcYquWNi15GQ8z6COY/Rtg==,type:comment]
  #ENC[AES256_GCM,data:wYJD8anCqKhblXdUIK1us8a0XwtT7+wf9Bl5Vs/rHP0tShga1tVjlyDCqzVyo+Tpt+UQV1Oq8tOMfeURMVV4UeR+E0gkZ4M=,iv:HKX42JlaI7UgRBpZkxU8eu/vCv3vIC+BnpXNGiZE258=,tag:I1LJ470PWF82R0jqJkVmiA==,type:comment]
  TALOS_MCP_CONFIG_B64: ""
  #ENC[AES256_GCM,data:VCav+7uksNl3ZGpCWOZIGbUgs9YsvgZnLkeIBm9tJj/5gtWZurjwxNigbeSX341qKSt7ahadqQsE/IpZKMOOdE8e1bzn4ljTzOE=,iv:GTQ1yZGo+q1TyfhC8SUAc6LgwWf0RfBGyf+pQYrC7+g=,tag:lUZqi0xbI59kG/473xX8dA==,type:comment]
  #ENC[AES256_GCM,data:eWY7ByIRuprmqFCkfT+EGqnawp01IDJEAI6fqL57wKPaw2rTJhJA/ja2rXwU6OfL7CBiZLrYGxVHxLemJ3aZ3WqSBSz0i8uGbQ==,iv:tN2PAA62GPZ+lAMacQpC5H3pC52b64WyD06ZaaakRL4=,tag:uQCiFf5Fq/sYFCgR09+BWQ==,type:comment]
  #ENC[AES256_GCM,data:UyTQ+H9AnFyC+Tg4zF29/zRvPXkryjARG/UulzMKEd+nVJmd5yxopEvA93JHGcNlILLZuUhn8VJPJacWsSZwcOtIYbuuxtPcKQ==,iv:OMPIYHaiNj+aKaaf+W29uhTu8s9gERon4Gh2OfcW17s=,tag:yHymJwKL65JQHzmZURleww==,type:comment]
  #ENC[AES256_GCM,data:KYo2gdtIqVFTx6jUa+Z48pLZG1+sRjr62aXwVQNZ7R3BInAut1WwmF6KWQN0iUknkF4IBHuG7MSX9/Fy/7MSxay7uwrThQRS3vLJRA==,iv:zVrgOSi4P6tG9radq32GpLnMjyxeh5WBwq84uWYmtoc=,tag:+ZHsmTZyz4J9JxFJ2NRD5g==,type:comment]
  #ENC[AES256_GCM,data:igjC3L48l1kLa7VUfGZ4S0+nLj/oXBI+jebPsKC1ZwKPoU4Lvj2Hm37K6T7JsBKuiMoDBW6rRxqLUIlC/Tdq08citQ6kTQ1SfQ==,iv:L40Ij0Y7LgihZvH/ry85JBouJESux9N7iCfjs2QJgX0=,tag:eXamqU6eMOkqrNXKXeSrdg==,type:comment]
  #ENC[AES256_GCM,data:GLJnpEBxi4E+5PVxgt0hNk3vjnhsz/FmCwT2hbKzDoVxVsoYjpB2BU01BJ/toLXVGfvvJz1wlAiJv7wZ3hiR4dCW9Td5BSg=,iv:fOwJsz9kTfDz5HvsFAP9oR+KShA+qtt9DiNi+NwEuiM=,tag:WlvW961/Ynu3KQcCt/Alzg==,type:comment]
  TALOS_MCP_SA_KEY: ""
  TALOS_MCP_OMNI_ENDPOINT: ""
  FLUX_SYNC_URL: ENC[AES256_GCM,data:JbiomgWItHawJFbCaxLstRlAvHXxOoZUjATkQbTk7iufKOXmrb3mkz7Wo6hL,iv:Auyq9AChHjkRy7KZdVTxhD5Y5qiTT0ZSoZ11yrlHFy4=,tag:f4ztodjr6HszsOogwf6Y9Q==,type:str]
  CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:jiBx9Mx8NQqKN4JEcEmz4oG0+n5S/DS4KieRZv7piuzLMxEycFkRRNXmzCPbb+vn2eX+7qqPga4VTunHI035I8yuyQG1zCTRO9eJZz53klOSVK+ZM56k9uxsRYUnBVX5A/L3wQofk/emMa+8tDNidqY1mOUKeA5ikXiAerbzBDQUvfbHR2L6tfHjdCrXGoBZRG30jojylNU8PggM+xg2dO1xNVEdo3LISgeulm//CcXYGfo/,iv:L7ZDVT21v3gEsFtFnw2ScDGg0hoeQd0vCd326Otlpic=,tag:bJbtFfY9SqLBF/KE4ms9VA==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:t704sKu67jt+ZtOfGR2N43LI8huHgL/5zvIVH0YT1qFiJOjm,iv:1yiEYEf9ooF8yToG7N+O83kQpxNcaKxtMIOA1hES9ag=,tag:aWzVqMO9YOSiClzrR9yauQ==,type:str]
  GITHUB_WEBHOOK_TOKEN: ENC[AES256_GCM,data:uDGFAcY+Vzx1RcGFO8Frm0trBpysA6j1ylX0vnRVO4rcbxwo9IosOVcaL7u+ijMbxtzLFs2kHjEOthkOIA++Ag==,iv:MgWso6S395UWz0881tcaTQt05Yq3iqiHeWicwPb+cw0=,tag:7IlQsNhguL9J2QQJFt7E2g==,type:str]
  POSTGRES_PASSWORD: ""
  TRELLO_API_KEY: ""
  TRELLO_API_TOKEN: ""
  TRELLO_BOARD_ID: ""
  LINE_CHANNEL_ACCESS_TOKEN: ""
  LINE_CHANNEL_SECRET: ""
  LINE_NOTIFY_GROUP_ID: ""
  ANTHROPIC_API_KEY: ""
  DATABASE_URL: ""
  SYNOPHOTO_AUTH0_DOMAIN: ""
  SYNOPHOTO_AUTH0_CLIENT_ID: ""
  SYNOPHOTO_AUTH0_CLIENT_SECRET: ""
  SYNOPHOTO_ALLOWED_EMAILS: ""
  SYNOPHOTO_FLASK_SECRET_KEY: ""
  SYNOPHOTO_NAS_USERNAME: ""
  SYNOPHOTO_NAS_PASSWORD: ""
  FREEPBX_MYSQL_ROOT_PASSWORD: ""
  FREEPBX_MYSQL_PASSWORD: ""
  CLAUDECODE_POSTGRES_PASSWORD: ""
  CLAUDE_CODE_DATABASE_URL: ""
  OMNI_GPG_KEY_B64: ""
  MQTT_LB_IP: ENC[AES256_GCM,data:mXrof5SE2/BQqg==,iv:Vva6SYVH19ld8cJAqHhL4ZH5T0wkJPh5h3Qf47zuUbI=,tag:37H910dOjRXq6xM67OQQdw==,type:str]
  INGRESS_NGINX_LB_IP: ""
  CLOUDFLARE_LAN_TUNNEL_TOKEN: ""
  DAILY_CHECK_SMTP_HOST: ENC[AES256_GCM,data:tc96CjcnQUGJ4NEihPI=,iv:ZYx+FqBKTic3YaXVHrbHudBaLE1GNT8P3vBTdmjWPRg=,tag:yyKSjDjPSPmxOF+pxc6zFQ==,type:str]
  DAILY_CHECK_SMTP_PORT: ENC[AES256_GCM,data:BTHX,iv:IHqLZcW6wb7m/z7kNER97bqc8Cu+s5zhfx2dW/L+mEU=,tag:p1rNTgEi3zZ8dd5Z83LJ6w==,type:str]
  DAILY_CHECK_SMTP_USERNAME: ""
  DAILY_CHECK_SMTP_PASSWORD: ""
  DAILY_CHECK_SMTP_FROM: ""
  DAILY_CHECK_NOTIFY_EMAIL_TO: ""
  DAILY_CHECK_HEALTHCHECKS_PING_URL: ""
  DAILY_CHECK_ENDPOINTS: ""
sops:
  age:
    - recipient: age1xn7sufdlltrdm3zwrxymhkyw8slret5a5856yrxekqmk9tz6culqypuy28
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSDhhRkNLSnZrWmYxS3RE
        QmxES0JtSDIwTHlOUjR0Q1ZIaHNtRk9DTVVVCnc5UWhMTENVUTNFZm5hODFyejA5
        bTJBc2N5bC9CYXBrblhKR0FOdE9pTW8KLS0tIFpqUCsrL0d6S1RqZm1PR3g5Qlhj
        bmFUckhXQmp2UjFkSW80QkluSUY3bFkKKLuwKHMSOPq/qmp9W5rqRWW2TPM4DX1K
        qulXBNLyLqsFB+7sjDrQaB4OxfWlUM0O4+0frtjnGsq04OM3O2CCoA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-16T22:42:36Z"
  mac: ENC[AES256_GCM,data:WpiPVVxl9WyEg1RalMKYFzgg9gE/MPOKNX0iuexQQg5l/DtZe+4N1wnFehS44myu15zPP/6WYvsrnHS3L0r2D1SHyhKr93eOi2c0SMA+UuytQ56qlo8etOqA3Ysjb543CzZvSR1vfr+DeJGvTDzkiTyQ9hTNJaqyhAmpysayZ9k=,iv:/2RKpTKwR0fXibExwVUyqKl2z5eFm06rDYe8FHhibLo=,tag:Kv1bpsh9Q7ZtdhMTnwAtqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
