apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLUSTER_NAME: ENC[AES256_GCM,data:rRy/5JBSjJAAqxdNtw==,iv:0z9SebzBK8brfy1wiV5+QP87+ae+tE8+VE6sw3/WmKk=,tag:agiYPsLXOG9B/XOE1tjjyw==,type:str]
  NODE_CIDR: ENC[AES256_GCM,data:fVQDRktt8G5ADdM=,iv:+EA3/ch/vyG6X8RWBzHy327AUP2YiXIxTMaCpzAcL/Y=,tag:LyUMFrPnRjKgCrPvOudvBw==,type:str]
  #ENC[AES256_GCM,data:O/u1dEREPJifR2m2k8iLaY0w4aPU2A1vlqy1Qpm2iSavFdUZoVZAAr8zqsPKQ0ZqVhHz+6fQxZVv1wXlRWRApVmX/5pkrfwg,iv:wOL8UtpnflUu9N1bXkjL2PGeEIOf5IdsG5HFN7asx3Q=,tag:bVk/fSm0K2J+HzVCcYlapg==,type:comment]
  #ENC[AES256_GCM,data:0YMebBSPVajxlThEOUfBei7qKNfl5RQwWV7BIggdhrPXMUk6JtkcSjBtHQJS2QYY/rH/Y40l,iv:6POP1y7BxFTQVb7Hwt/uvRY3HuSJgsBrFTpb+7gjKgc=,tag:0LqSZ+GZF+631S8c40WMfA==,type:comment]
  NODE_DEFAULT_GATEWAY: ENC[AES256_GCM,data:pFbgr/RzGkU=,iv:OqjhnlJ0cGbZ3ANKl0LJcfwihYh5z+1mApahIr8xNv0=,tag:DHqle9QXv5twIZC9h5irnQ==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:ll6G8RTLFznn/g==,iv:bcL+0cHgKaTvskoDIuyXVmqH+nvCye/g+1wFD32t/Wo=,tag:a+sc7AJFjo4M/3Myq1B19g==,type:str]
  CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:WYmgSkU6alHlurTX+0b8/sr32//ik3mQ8aqQIenWNtnJz5SqJtgQrTdXoOKv25gBsLMVQBM=,iv:9JRuVLri3AxegYu2a4TLo3PjFM5bN69GcnbM2ewIum4=,tag:lGMIws0Eimd2hpm1DhfT0A==,type:str]
  #ENC[AES256_GCM,data:9QlmlaRxrl9do6lMWQM2kr06nKwWeZ8E9YmmqROSdHbIiGPG/NfG8clczrkqaUSOT38fYsOSgrmh8LqEz4hFsjjJDL7hD3xILFOlNA==,iv:4gabhhb4YDixwSETLNiTougdITL5G/ZmtqFRhFjYTT8=,tag:o4gZm/M/EBSrVMSQIW2hUg==,type:comment]
  #ENC[AES256_GCM,data:6wifSQCV9XixU+J0l7L3Dqr7O+6KkReTAOfeELTRQsGEDw9h5g+S5Fbcjth18OCqM8UDu/z/qJeaTZFV/8eAi41+w2NyoCC0,iv:RNNDH4+e2bPFR/x8SJ+G/cwRJI7KpbMwBTkoHXtlwAc=,tag:bO7fPlV40MjIzO11NB+LSw==,type:comment]
  #ENC[AES256_GCM,data:uXEuTg5LhvMvnq+NX0+LFmDu24rxiCf5tRR98rHVryTzh8WkkGWRdGSJGN9CHvJ9T/S1ZgREro/oFg2ifvlts4r6X/uAibuv+2Uqkg==,iv:2K3kPTn6N1iRbj8PWq/fHEKCUWd4/OCStAyZhZAhISw=,tag:TN2eO9WpGQHgyVLdkmmDRA==,type:comment]
  CLUSTER_API_ADDR: ""
  CLUSTER_GATEWAY_ADDR: ENC[AES256_GCM,data:BE28XWzW+8ZzNQ==,iv:/30FKjDzFYaiaTJFSQCo3hipu3lAovEGg7wzyaNa4uU=,tag:+t83XSDmxCGiOtNSKVsNoQ==,type:str]
  CLUSTER_DNS_GATEWAY_ADDR: ENC[AES256_GCM,data:qDciyFc/mvYEng==,iv:Wj5r1Xlbh8mIEj1IZ8k/W00pr7j3SaPNxQJ1CyiP8ps=,tag:XpixDZ1P/vBOfhtp4A5VnA==,type:str]
  CLOUDFLARE_GATEWAY_ADDR: ""
  COREDNS_CLUSTER_IP: ENC[AES256_GCM,data:W8WxibczuBk9AQ==,iv:h09zEgNL7cyFSETxgSFjakLLMl5eMXP69d+3hZ9Ft3Y=,tag:xDxxJxbi8wYXhYHRxeCpeQ==,type:str]
  #ENC[AES256_GCM,data:DyNb37bCWBnB2pGxGx9Ve9ZtV80vtlNeWb4zTYV8l46T0x57jJ/QrfBkhnWDZuHwvwzmEY1OX9p2OJuw6QlVZOysLXJnghW8,iv:3yiduTUKoMxMpvvtiP1hbPog3FypxsH5d3MEQsUFo9w=,tag:g4rxxTHzUgk4+sTaz31U/g==,type:comment]
  #ENC[AES256_GCM,data:I0Yny9Jg3CCMIuMc9teIBpbqGClw6K4ywKiJNzEdDkjFfnPU3vWtHf12m8nCn0NGYV5S3cvmbGhk5hDcN/UNBiN02NcUOQ==,iv:UyYR7FQGmizDetFtCnuPoTgeXe31SdKT+hwiZh5l5mg=,tag:/DHCtr99CVrKwY2Nn9ajDw==,type:comment]
  #ENC[AES256_GCM,data:nWqssAMbiF36m32dQbsLAF8exrt8/TtmekAB8kMaAxdkWYYL4ILPeqpM3TQQvwGqPMFDmc7t7CPhbrcQKSVbY5COhkSxYF5kfQ==,iv:AzLB/o6TDgydHQt+GFi35/EaiCPproWbUy7zf5Yw2U4=,tag:oVgVfqKkTwmXQ0GBxuSWIg==,type:comment]
  #ENC[AES256_GCM,data:lU0/okZ0jqjXDtmzuR8mRU5HoNEGbuasQNCcVj0cEmkR4UrRD1V7DOSPRvc5pKDZ6fSXdImsF/oNH6k+Fx6WCECrI1ZNAkPfsP0=,iv:qWUri0VdlnhEGbPqBwKj2unjkIKJmx5s5NH40aeHgkU=,tag:Cb8knrvD45fx0K878J2z3g==,type:comment]
  #ENC[AES256_GCM,data:rPCcA67YtPxk3rPYAFM81eZeUyAdz17FuFrnOmHo7N8MWe3JxxdLt0MIeOni4LNUAR/ckP0HH+uy,iv:V9om79JfIerfQjk14uo9hcX7IkT/qbeejE1suUb8Ro8=,tag:y745wBwTDAOcxE8EkT3lpw==,type:comment]
  #ENC[AES256_GCM,data:35NT3e38Rn8N0mkRtGM4VCiuesm+/mz3IhKD2XC5VN0m47Q3UnWYoi8vbs4dRVXarrdWcISWON+c0ieZas0S/FX7FzlROkk=,iv:EwceA/jk1SPUK+FRxtwwSATj8B1Mb5MVMbGG6SZ8Z6Q=,tag:3NFZG/WhgAFqBLf53WcxoQ==,type:comment]
  #ENC[AES256_GCM,data:OxkLM3EYvsEFqUR92TXZN9QpuxdXZLGAEd4S2+VNY5zU/0fMwGKjfX8YVtS4uoDCXxhQQ8Ws/gGzOD4fNSdOIuf/reZrHPc=,iv:LKvTahNCjIK0eFA6eVBVVu7Ua/khvscjOXsBjfKdCjg=,tag:Nojd4/Cj3OkU+6dM4/uAlw==,type:comment]
  ENVOY_EXTERNAL_SERVICE_TYPE: ENC[AES256_GCM,data:ofolIx0hG64CiZrA,iv:wr0U9EWyWprkeeyKKLNso5rWDWYch886dAcV/g8b2Jg=,tag:yyCmrI6qIs+PgSUWQ2ohxQ==,type:str]
  LAN_SHARING_KEY: ENC[AES256_GCM,data:IJqC,iv:Lfxabn5YN5Vo+Y3qZND0jlQPeNY0pb0vubLFq9Mm33w=,tag:NvlilNs1OnRZx4N+wh5Jdg==,type:str]
  LAN_SHARING_CROSS_NAMESPACE: ENC[AES256_GCM,data:TzerY6gERND14wOr,iv:F5Fs7XOnd2UnWx+/tsDxnBmgRjYPFW2FtNqnF3oLD2E=,tag:mCnO1ILxnkg/6SySzB5JTA==,type:str]
  LB_POOL_BLOCKS: ENC[AES256_GCM,data:Znlt9gJlkByRP5yIjuglC8Ost0ZiRgY3yVnAwrSroM7hPcSLewL1Ph670ko=,iv:b3Mvb7bHde99yCeylvBTNIf7Fnm5mJK1GZcWrSzIIoA=,tag:0HoFSk+JCild/6Xoyjsi1g==,type:str]
  MARIADB_LB_IP: ""
  OMNI_UDP_LB_IP: ""
  #ENC[AES256_GCM,data:8Tc5T+CKC2e4jiwo4bX3IlpQdsy1oeoEX5e80SbXY15PNYxredi4C6gfvvMzNztt9E3yhQvo83TfTUQAHA==,iv:rrAbOeNsQcAAh0VG7WWwM5mNELXkBnEfnLtUeZMCR/g=,tag:Iz6vgT797EkIa9UD0ZokUQ==,type:comment]
  #ENC[AES256_GCM,data:PwzYwwgjhLhOYIXnQqaUQfIfnBTkpo6igxFh+Rj0SLCdQuXqJzNKWjU6TzEiMWO2ZGEK+lfxGGeVxoE1nkMb3rY=,iv:L+ta29r5aSkrLzaoC8ljqtpI0GPrPVMeAvBqWO1asGc=,tag:hnMJQlkjgq6B6/KzeZM1aA==,type:comment]
  DEFAULT_STORAGE_CLASS: ENC[AES256_GCM,data:aYUGx+UoLvvFIg==,iv:WE0bxMb5wtqY+Ae0oIR6eYNIHt140T7kQ5Gg6mqMVxw=,tag:IRWL16KHrWD1+/ymip6WsQ==,type:str]
  DB_STORAGE_CLASS: ENC[AES256_GCM,data:/6hRPxQRlzc+XA==,iv:BXHQqn5TuceoTzUdO9H2fn8L85bnow/WipsZPlAs3j0=,tag:DSBY3JXr4MJbQ7qYidYZvg==,type:str]
  LOCAL_PATH_IS_DEFAULT: ENC[AES256_GCM,data:N54I5Q==,iv:G2es53WqvAwkMux80rSAOoOdjhPDt1DjaLhlysxXPhI=,tag:mLIupYQPGhgJSEcVQkasZA==,type:str]
  #ENC[AES256_GCM,data:repHIUEzZ17K0YeMB5FaPylxOiHsv1Viudwxre5hAEPFdACzSpM=,iv:YrgQmAn13EtuBbtBzI2HSq4P2Qlgdhc+03JzV0IAaK4=,tag:nMZwNeWS1MGjoI/CfIRL2Q==,type:comment]
  NAS_SERVER: ""
  NAS_PATH: ""
  NAS_CODING_PATH: ""
  #ENC[AES256_GCM,data:otk/r0jxd2bHlEBKxeJC529XVMP4h6klz1dDkk0WtSXxQ2DYie5J4DCvCsqwOsjNAs/a6iX0OdGo/BnvpP+d4IcPvhbQ5Bsc8MHw,iv:aTr6COsI6rJaFArg9cIW+Q5qpKHjduifaMlBm6FkOfM=,tag:PGUki7m/CGw1wgvGIISCog==,type:comment]
  #ENC[AES256_GCM,data:VBTR3Ue146jAs2lEIAH+07KJz1KRPH2jUJVn0ys2oulcnIfyNwLVk5uTN4fMuA2vFsPONDcd96u3ICOHSy0o1A==,iv:WVcIxhbnZb//BCtencvAYhs5xd1rHMBhYUSFSOsJok4=,tag:j88waIQ4RbolVtV9Rz04HA==,type:comment]
  BACKUP_AGE_RECIPIENT: ENC[AES256_GCM,data:63vF/YLCQU0VHNQ82lBNcDzaNgrMtz35nivpBzol7lIbWoqsbbcw7Eqq/HdD5OerBLk0qPTmoSDNsIAZjKg=,iv:Ua4PON48z8z6eU5hFZuQoSIQKynwXI2mOG8ThJZ/NNo=,tag:vgTFntC/egiSmUkcWIEz+A==,type:str]
  #ENC[AES256_GCM,data:E3IommT1huCf6+MxYBF6H9W8MhJy0hYYYzx2h3WVvkyc/UHibMVOoNBF8u9dNSKC/np90IUBsApKVN/o0HIXU/DGsgo=,iv:Noho+C5209ZYcK7B4NnlLB3QcJY2Fuu9Fo1NyTELOyY=,tag:HoHwQsetf+4hdkSEIys38A==,type:comment]
  BACKUP_R2_BUCKET: ENC[AES256_GCM,data:RdlPH4ca0eVk6Ww5M/SEXCaImY0=,iv:KsS93yxSK/R8qSQ3lP1vfHgYFA6WSAxSfmmkDnzLOjE=,tag:1RXHPoOuPx6S8Y/ssVIs2w==,type:str]
  BACKUP_R2_ENDPOINT: ENC[AES256_GCM,data:brWJGpekc119ABS1P5SSnFU2rwA907HxQK5WOb7mjF+TisxqKjY7+LeqzZCfHUIi1P0F/lmHvA/FvTK2uHXgb70=,iv:HICv6pMVgKMdVSas6kQr9m4KPHM/eFMJW7Vkhr4iYAI=,tag:yqBdoT45Gyyo0TBBXOv2Iw==,type:str]
  BACKUP_R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:3312mg/PRfNR4n/IH/MP5NT8q0Bbtb+WWcq9VMJmOJ0=,iv:8YjSb15IAIkO4PyoBJHdlZMqx75fsXbPEDTcMkK4zpI=,tag:vV8ORIsJW4cUK3wDrF3Hfw==,type:str]
  BACKUP_R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:jzl/6Y7CnaGG/EsYeetkBl8k1KqZCb5go9Vb57H3bx4GFhNmWkYVIrL4NCQ9hRAV7cbxo7rVtoWTEhriV2Rfgg==,iv:BnELDHI9nMOl2nQCpRZvdNbXhE2Riq75jXb78ApGr9E=,tag:FvQ9sn6oo4kihgFZzUOzTQ==,type:str]
  TTYD_CREDENTIAL: ENC[AES256_GCM,data:VFmMpj+A5O2yWu5sWmi/yKiEuYjn0LcYxLtInZFkR5e8iNc5,iv:q6ElFGFzS3JZwmMDOEJPKy05DCX0WFbczWRJ7dZ1an8=,tag:bcO9G06lqy43UhckARJ0Iw==,type:str]
  CLAUDECODE_AUTH0_CLIENT_ID: ENC[AES256_GCM,data:e8tPbam7su/2LikdWJs03R8vgQe1rQXtGJQdYzf5Lfs=,iv:gGfRcVQE+o4ZSLcD0RXjlpmMCbWKJadnEvnk80Igf14=,tag:yYlzUfND3bAUBVwyJroSYg==,type:str]
  CLAUDECODE_AUTH0_CLIENT_SECRET: ENC[AES256_GCM,data:CQNh9Sd7TDs84LPL+1gileRVV3fPqZWh1Fa9/24jYdjkBJBvoPja+VCGaSo5CHTBSKQsLc9TUJV+/cDYduDzMw==,iv:qwJJwtoDSZHhCqTB3kBxSzjxBgLmhPy58Rhb9hUMgGQ=,tag:bndUv73dG1vOUyULMkCkvQ==,type:str]
  CLAUDECODE_OAUTH2_COOKIE_SECRET: ENC[AES256_GCM,data:laogNzWFRZQaf5JM/9fcva7X+jtwSKPYOE68pFb/Nrree5CIW14V4Fk9XQo=,iv:Xx0g/JcWhB62yDYgM8vuBVTAmB6NTiwTtwgZjFaqh1k=,tag:XKPJk5rTBjCmcC7Kh9zOZQ==,type:str]
  #ENC[AES256_GCM,data:OuTb6SE/eqCWNaxvBLx/FbD6vkn6ykXXZ9610lWayp480t7xLfAKypaiY8465q/Uw/6qjwtD7GKPLHIibtaCumETow==,iv:8rxOs66Kr0MH4BjeeKDIpb1laVFSn/77XzvY822HTrg=,tag:nca0r1uv5d8RWZ5CG/M9kA==,type:comment]
  #ENC[AES256_GCM,data:0JFvgpGV//ocWMIS6ApCOkKuRHGpnVJj2QNugq8Ce1XlBAc4FQrOcrNfYjeG5QoZpmwbaLIHzfONLL0FD4pX5hqO7xwB,iv:JP6sme5wdJP7rXrSCPrzHS6R5TLIedNlQRmtJjC4whk=,tag:0l9mMLi8PGNQ/qLmo4F18A==,type:comment]
  #ENC[AES256_GCM,data:jRLecosS2j+JMTj3iWQMTP19OLUtMXERUOv4jw40yUSSPWIp6ZXp8QSmfqiVEBwi9x/0fqJJR2tgXv7N7I84QvTjAWTB7Xc=,iv:pj5p4mlPdQvg3OsDKda43Sw6JhdchZLUFkbp/iM/TuA=,tag:BS3Iogn6uyfwEAkoi+1X8g==,type:comment]
  TALOS_MCP_CONFIG_B64: ""
  #ENC[AES256_GCM,data:YHI0i8F/nKAbijF+Whn3wWl7dZ4gztWDdDhpuSOTgIvIQgdPVcniNlDj24Xt/7lB8SgdRftaVXgGgQ3WSeH60M0NXZ6t+/LKIoQ=,iv:vfzPN2mhnquowhNg/+4zpx6BRF3ms+cKN1uVNmE77P8=,tag:izklt8PVvoGtxV+3y4npOw==,type:comment]
  #ENC[AES256_GCM,data:TT4UOReCenL9vHuFB/Xx26kr63cjVCLQf3lrPNfJkxHCb741ifeR8H3h7iwhJ1BcCqp1CVtl3jMkwO+GgXYFDUXrnuR3bZQ7Tg==,iv:/yoxvxMRti204TtrfUSFqYUxWIGyCOfonnQV9ow7vmM=,tag:pBt6LRhYS25OTZ2ikoYDKA==,type:comment]
  #ENC[AES256_GCM,data:57FfLDmg6+D/qLvNmraPzGv5TNB3KHTBTYzN6ZvkaGlo2gGN20kg5XAPbj6hH4YQNC9yZs5qS7faZBAKayFbrZPyCm6fD39oAA==,iv:hVp2VzajtMUGpCB/jCRdElegjJgikYQ28koX4A1AWwY=,tag:VJOKfuhy01GGKS8feupgqw==,type:comment]
  #ENC[AES256_GCM,data:I/vN7SycRSHEL9vcHZlHjQo5hN7vCyDY786IjILGU1Mj652BcRV+35eLFAnVbz2GgyMbkOljRTZzxCHwHqarbJjLPW5mmrqwdvttaA==,iv:M+Bz6zSQW6FwF0+Zhv1n3PORiiJQc1yOq6rgKyol1fg=,tag:tfySzHDsghEQksDzHa4qlg==,type:comment]
  #ENC[AES256_GCM,data:wS7umKKJWW7b0SW/opRzseX5UHKjyjmvhWoA1aMeyqxnDz0gGJvLvYBCun/rmhg0mRE9fTrDl4V0pMXki8bGS8ysdcgrkCE8jw==,iv:9aiInwuhiMpTmMgdJEykb2ttoK+IkmRgVdGCHC2cS6w=,tag:mgaGgbhj4ZOeIJLv5dcBcg==,type:comment]
  #ENC[AES256_GCM,data:eQWLX3V6EU3Tv4QzPoZzS2vQ14VQLNPzNsRpyhvvh3d72IcM18BDgx9GgT55AJcrGovMBLsyybKbIiQC5nmRBN0a/9E61ME=,iv:Hltb5nZenlZFwqqrRNJFAWjHb4DD48F/8S/Oct92P7U=,tag:yuo5nvs5s9/kU929fqk5pQ==,type:comment]
  TALOS_MCP_SA_KEY: ""
  TALOS_MCP_OMNI_ENDPOINT: ""
  FLUX_SYNC_URL: ENC[AES256_GCM,data:oPFPJBxw+jSNxz9t9SWHU/jEFTB+QfYzD1eKLVXzhG6ySdmIDS/+ZVUHtoPL,iv:qetz3weleDgqJGvLUfBpuVP7Smju54toYaN4xyLB5Y8=,tag:x3TGnWPHVEI1zdbwG3nC4g==,type:str]
  CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:IofZdczQX7Xic0gWziAYaIJZFTK829+M3fgydou98AJ22rHMQ7ighzyKkq6b8+i7N3stZaiE786bmut+zSupJFSxF3Sq2FpAuzInYx4xiDFqH3teWOEAfKqTR0/V5lbxggDGFRrIqQOWODyYDDgE2CggmrgANTS0LbG7bWQkdUR9hEamnCqMq1vqHi6sI8KFxQISIe8g5GB9qQ/WOAYcmdXRzecZUbutkGamoSBYbfL6+PQg,iv:shZabPBYT2Z1wy3L8XyefYBlwSrrK9evvNJ1n3fRuSY=,tag:GiApcdEAT3vBG6FizKozgQ==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:MdYOsuf2yOlRT1FmPmZr92zs3W8r+Lhzz0TG/4YEAm9Pgfh9,iv:3n+415Kx5VJi5iwSYGq0mfAkxdBBwLPOgVoyNVCxT7Y=,tag:sOK3r2VNr++/k75qAkakNA==,type:str]
  GITHUB_WEBHOOK_TOKEN: ENC[AES256_GCM,data:nohX4Qtwnw0yEnUOBR7BUz+KEcdffDzdDazlADQ8aihngDNAxkROhAB9Uz342bfmlTCbIFP6fqelW6Ub81Bx+A==,iv:ksA+2DdjLdWm4AWVtunHdJCwe/Uh+5CUegMKj6C05MI=,tag:cuxVu2JADQcnC3uZ365GPQ==,type:str]
  POSTGRES_PASSWORD: ""
  TRELLO_API_KEY: ""
  TRELLO_API_TOKEN: ""
  TRELLO_BOARD_ID: ""
  LINE_CHANNEL_ACCESS_TOKEN: ""
  LINE_CHANNEL_SECRET: ""
  LINE_NOTIFY_GROUP_ID: ""
  ANTHROPIC_API_KEY: ""
  DATABASE_URL: ""
  SYNOPHOTO_AUTH0_DOMAIN: ""
  SYNOPHOTO_AUTH0_CLIENT_ID: ""
  SYNOPHOTO_AUTH0_CLIENT_SECRET: ""
  SYNOPHOTO_ALLOWED_EMAILS: ""
  SYNOPHOTO_FLASK_SECRET_KEY: ""
  SYNOPHOTO_NAS_USERNAME: ""
  SYNOPHOTO_NAS_PASSWORD: ""
  FREEPBX_MYSQL_ROOT_PASSWORD: ""
  FREEPBX_MYSQL_PASSWORD: ""
  CLAUDECODE_POSTGRES_PASSWORD: ""
  CLAUDE_CODE_DATABASE_URL: ""
  OMNI_GPG_KEY_B64: ""
  MQTT_LB_IP: ENC[AES256_GCM,data:kZU84p/J9w043g==,iv:fnxsoVzaAq0+vgmUovLubPvQtU2k7WWC5dYM/udM/s4=,tag:tjiAlOVXP7g+CjD0Xjabgw==,type:str]
  INGRESS_NGINX_LB_IP: ""
  CLOUDFLARE_LAN_TUNNEL_TOKEN: ""
  DAILY_CHECK_SMTP_HOST: ENC[AES256_GCM,data:++kFaAwGkjASomVTvW4=,iv:6PkjIt4Agye9+QI3uSs96TLnqKS1UOy7e+8qNqt64lM=,tag:G7sDo+OOYIiaKLrwBtHEEg==,type:str]
  DAILY_CHECK_SMTP_PORT: ENC[AES256_GCM,data:0FjF,iv:1tT17fs+Oi7tJIektrP0pu8ehj6rcCy7SYvDTuQMX+0=,tag:BMQgqey6Qp7fuDKLg5Huvg==,type:str]
  DAILY_CHECK_SMTP_USERNAME: ""
  DAILY_CHECK_SMTP_PASSWORD: ""
  DAILY_CHECK_SMTP_FROM: ""
  DAILY_CHECK_NOTIFY_EMAIL_TO: ""
  DAILY_CHECK_HEALTHCHECKS_PING_URL: ""
  DAILY_CHECK_ENDPOINTS: ""
sops:
  age:
    - recipient: age1xn7sufdlltrdm3zwrxymhkyw8slret5a5856yrxekqmk9tz6culqypuy28
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYmhoWVdLdmZPRjBvb2JU
        VFV0UTA1YXBHVkxhZW1lTk9CL0FuOGFXWlEwCm42RkROa2tsalYwcXRjTEV2SEgy
        Z09EeS96eklLY3VpamlQRFNsOFVST2MKLS0tIGsrdnJJYjRoR2pNNTlxK1dHV2dr
        RzlXeEJ0NFA3UWFvUGtsbEJuY1JyMU0KfYxppt1s8UGv0XH0JiSG4P2E6SZAGTf+
        JyEnCJ0ZTq7gOURl9gcdh6o6kD5wH2odTGPcjMZVr55UChEgcnfRNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-17T03:33:58Z"
  mac: ENC[AES256_GCM,data:9jpWySnNOp1M9+J/Mvv9rVjuokWgzOSK9zGHkAQoqUSnuTdOMmYSt5P5sX58y1xLQlUIv5iFxdfEOoy3WtIC6SOxttX3rfiIP0sbZODR9iUMpPTzBrEGD6q/d/j6WSKNuQMMFB2c2mrxXUt9mwxrci5l7u8wGeZYq4xnhUr1MEg=,iv:pwsVdBgEHrExYthluLa9xcxAez8aorpe1BPnYsoDGe0=,tag:IuppxMeSzxrtgFZqWseQNw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
